language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - build-tools-26.0.2
    - android-25
    - android-26
    - extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
    - ./gradlew build dependencies || true


before_install:
    - chmod +x gradlew

branches:
  only:
    - master
